on:
    push:
        branches:
            - main
    workflow_dispatch:

name: Deploy Server
jobs:
    deploy:
        name: Deploy Server
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
              with:
                  submodules: 'true'
                  token: ${{ secrets.WORKFLOW_SUBMODULE_ACCESS_TOKEN }}
            - name: install node
              uses: actions/setup-node@v3
              with:
                  node-version: 20
                  cache: 'yarn'
            - name: Enable Corepack
              run: corepack enable
            - name: commits
              run: git log -15 --graph --pretty=format:'%h -%d %s (%cr) <%an>' --abbrev-commit
            - name: Authenticate on GCS
              uses: google-github-actions/auth@v2
              with:
                  credentials_json: ${{ secrets.GCP_MFLASH_PROD_JSON_KEY }}
            - name: Build and Deploy
              run: |
                  yarn install --hoist
                  touch app.yaml
                  echo 'runtime: nodejs20' >> app.yaml
                  echo 'env: standard' >> app.yaml
                  echo 'service: default' >> app.yaml
                  echo 'instance_class: F2' >> app.yaml
                  echo '' >> app.yaml
                  echo 'env_variables:' >> app.yaml
                  echo '  NODE_ENV: production' >> app.yaml
                  echo '  APP_URL: https://mflash-api.riker.tech' >> app.yaml
                  echo '  SESSION_SECRET_KEY: ${{ secrets.PROD_SESSION_SECRET_KEY }}'  >> app.yaml
                  echo '  MONGO_URI: mongodb+srv://${{ secrets.MONGO_AUTH }}@memoryflash.r6ngiew.mongodb.net/?retryWrites=true&w=majority&appName=memoryflash'  >> app.yaml
                  echo '  FRONT_END_URL: https://mflash.riker.tech'  >> app.yaml
                  echo 'automatic_scaling:' >> app.yaml
                  echo '  max_instances: 1' >> app.yaml
                  echo '' >> app.yaml
                  echo 'entrypoint: bash -c "cd apps/server && yarn start:prod"' >> app.yaml

                  # Build server
                  cd apps/server
                  yarn build
                  cd ../..

                  # Deploy within the apps/server directory
                  gcloud app deploy --project "memory-flash-436000" app.yaml
                  curl https://mflash-api.riker.tech
