name: Unit Tests

on: [pull_request]

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write

        strategy:
            matrix:
                node-version: [20.x]
                mongodb-version: ['6.0']

        steps:
            - name: Check out code
              uses: actions/checkout@v3

            - name: Enable Corepack
              run: corepack enable

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'yarn'

            - name: Install dependencies
              run: yarn install

            - name: Run tsc
              uses: icrawl/action-tsc@v1

            - name: Build React app
              run: yarn workspace MemoryFlashReact build

            - name: Build server
              run: yarn workspace MemoryFlashServer build

            - name: Start MongoDB
              uses: supercharge/mongodb-github-action@1.8.0
              with:
                  mongodb-version: ${{ matrix.mongodb-version }}

            - name: Install Playwright browsers
              working-directory: apps/react
              run: npx playwright install --with-deps

            - name: Update Playwright snapshots
              working-directory: apps/react
              run: yarn test:screenshots:update

            - name: Commit and push updated snapshots
              env:
                  # expose the PAT for the push
                  PAT: ${{ secrets.MFLASH_CI_TRIGGER_TOKEN}}
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"
                  git add apps/react/tests/*-snapshots/* || true
                  git commit -m "chore: update Playwright screenshot snapshots" || echo "No changes to commit"
                  BRANCH="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
                  echo "Pushing updates to branch: $BRANCH"
                  # push over HTTPS using the PAT so GitHub treats it like a normal user push
                  git push https://x-access-token:${PAT}@github.com/${{ github.repository }} HEAD:"$BRANCH"

            - name: Run unit tests
              id: tests
              run: yarn test
              continue-on-error: true
              env:
                  APP_URL: http://0.0.0.0:8008

            - name: Authenticate on GCS
              if: steps.tests.outcome == 'failure'
              uses: google-github-actions/auth@v2
              with:
                  credentials_json: ${{ secrets.GCP_MFLASH_PROD_JSON_KEY }}

            - name: Upload screenshots and comment
              if: steps.tests.outcome == 'failure'
              run: ./scripts/report-test-failure.sh
              env:
                  PR_NUMBER: ${{ github.event.pull_request.number }}
                  GITHUB_TOKEN: ${{ github.token }}

            - name: Fail workflow if tests failed
              if: steps.tests.outcome == 'failure'
              run: exit 1
