name: Unit Tests

on: [pull_request]

permissions:
    contents: read
    pull-requests: write

jobs:
    test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x]
                mongodb-version: ['6.0']

        steps:
            - name: Check out code
              uses: actions/checkout@v3

            - name: Enable Corepack
              run: corepack enable

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'yarn'

            - name: Install dependencies
              run: yarn install

            - name: Run tsc
              uses: icrawl/action-tsc@v1

            - name: Start MongoDB
              uses: supercharge/mongodb-github-action@1.8.0
              with:
                  mongodb-version: ${{ matrix.mongodb-version }}

            - name: Install Playwright browsers
              working-directory: apps/react
              run: npx playwright install --with-deps

            - name: Run unit tests
              run: yarn test
              env:
                  APP_URL: http://0.0.0.0:8008

            - name: Authenticate on GCS
              if: always()
              uses: google-github-actions/auth@v2
              with:
                  credentials_json: ${{ secrets.GCP_MFLASH_PROD_JSON_KEY }}

            - name: Comment screenshot diffs
              if: failure() && github.event.pull_request
              run: bash scripts/comment-screenshot-diffs.sh
              env:
                  GITHUB_TOKEN: ${{ github.token }}
