name: Unit Tests

on: [pull_request]

jobs:
    test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x]
                mongodb-version: ['6.0']

        steps:
            - name: Check out code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'yarn'

            - name: Enable Corepack
              run: corepack enable

            - name: Install dependencies
              run: yarn install

            - name: Run tsc
              uses: icrawl/action-tsc@v1

            - name: Start MongoDB
              uses: supercharge/mongodb-github-action@1.8.0
              with:
                  mongodb-version: ${{ matrix.mongodb-version }}

            - name: Run unit tests
              run: yarn test
              env:
                  APP_URL: http://0.0.0.0:8008

            - name: Install Playwright browsers
              working-directory: apps/react
              run: npx playwright install --with-deps

            - name: Run screenshot tests
              run: yarn workspace MemoryFlashReact test:screenshots
              env:
                  APP_URL: http://0.0.0.0:8008
